### ISSUE TITLE
antsRegistrationSyNQuick dependency for new hippunfold branch

### ISSUE THREAD

**Issue by jordandekraker** [khanlab/autotop_deps#4]
this needs to be added to the dockerfile please! I don't have permission to add it myself

**Comment by jordandekraker** [comment]
https://github.com/khanlab/hippunfold/blob/8e41f6ee79f087e089c9d536112d649fb47642ca/hippunfold/workflow/rules/gifti.smk#L577

**Comment by akhanf** [comment]
I've updated this in #5, and made a release for v0.4.3 - can you try with that container?

**Comment by akhanf** [comment]
docker://khanlab/autotop_deps:v0.4.3

**Comment by jordandekraker** [comment]
works perfectly. thanks!
